apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  image: aidanmelen/strimzi-kafka-operator-aws-msk-iam-auth:0.32.0-kafka-3.3.2-aws-latest
  replicas: 1
  bootstrapServers: "${BOOTSTRAP_BROKERS_SASL_IAM}"
  template:
    config:
      group.id: connect-cluster
      offset.storage.topic: _connect-storage
      config.storage.topic: _connect-offset
      status.storage.topic: _connect-status

    # Uncomment for EKS IRSA credentials
    # serviceAccount:
    #   metadata:
    #     annotations:
    #       "eks.amazonaws.com/role-arn": "${AWS_ROLE_ARN}"
    
    # Uncomment for IAM User credentials
    # connectContainer:
    #   env:        
    #     - name: AWS_ACCESS_KEY_ID
    #       value: "${AWS_ACCESS_KEY_ID}"
    #     - name: AWS_SECRET_ACCESS_KEY
    #       value: "${AWS_SECRET_ACCESS_KEY}"
