apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  image: aidanmelen/strimzi-kafka-operator-aws-msk-iam-auth:0.33.0-kafka-3.3.2-aws-latest
  replicas: 1
  bootstrapServers: "${BOOTSTRAP_BROKERS_SASL_IAM}"
  config:
    group.id: connect-cluster
    offset.storage.topic: _connect-storage
    config.storage.topic: _connect-offset
    status.storage.topic: _connect-status
  template:
  
    # Uncomment for EKS IRSA credentials
    # serviceAccount:
    #   metadata:
    #     annotations:
    #       "eks.amazonaws.com/role-arn": "${AWS_ROLE_ARN}"
    
    # Uncomment for IAM User credentials
    # connectContainer:
    #   env:        
    #     - name: AWS_ACCESS_KEY_ID
    #       value: "${AWS_ACCESS_KEY_ID}"
    #     - name: AWS_SECRET_ACCESS_KEY
    #       value: "${AWS_SECRET_ACCESS_KEY}"

  connectCluster: "my-target-cluster"
  clusters:
    - alias: "my-source-cluster"
      bootstrapServers: my-source-cluster-kafka-bootstrap:9098
    - alias: "my-target-cluster"
      bootstrapServers: my-target-cluster-kafka-bootstrap:9098
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "my-source-cluster"
      targetCluster: "my-target-cluster"
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
          sync.group.offsets.enabled: "true"
      topicsPattern: ".*"
      groupsPattern: ".*"