name: Release
on:
  push: 
    branch: main
  pull_request:
jobs:  
  docker_push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        strimzi_version: ["0.32.0"]
        kafka_version: ["3.3.1"]
        aws_msk_iam_auth_version: ["1.1.6"]
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          build-args: |
            STRIMZI_VERSION=${{ matrix.strimzi_version }}
            KAFKA_VERSION=${{ matrix.kafka_version }}
            AWS_MSK_IAM_AUTH_VERSION=${{ matrix.aws_msk_iam_auth_version }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:${{ matrix.strimzi_version }}-kafka-${{ matrix.kafka_version }}-aws-${{ matrix.aws_msk_iam_auth_version }}